/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button'];
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions'];
    ASpace: typeof import('ant-design-vue/es')['Space'];
    DButton: typeof import('vue-devui/button/index.es.js')['Button'];
    DSpace: typeof import('vue-devui/space/index.es.js')['Space'];
    ElAside: typeof import('element-plus/es')['ElAside'];
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb'];
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCarousel: typeof import('element-plus/es')['ElCarousel'];
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem'];
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElFooter: typeof import('element-plus/es')['ElFooter'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElHeader: typeof import('element-plus/es')['ElHeader'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElImage: typeof import('element-plus/es')['ElImage'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElMain: typeof import('element-plus/es')['ElMain'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElSpace: typeof import('element-plus/es')['ElSpace'];
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
    ElTabPane: typeof import('element-plus/es')['ElTabPane'];
    ElTabs: typeof import('element-plus/es')['ElTabs'];
    ElTooltip: typeof import('element-plus/es')['ElTooltip'];
    Header: typeof import('./../src/components/Header/index.vue')['default'];
    'Index.bak': typeof import('./../src/components/Header/index.bak.vue')['default'];
    IxButton: typeof import('@idux/components/button')['IxButton'];
    IxSpace: typeof import('@idux/components/space')['IxSpace'];
    NButton: typeof import('naive-ui')['NButton'];
    NSpace: typeof import('naive-ui')['NSpace'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default'];
    TButton: typeof import('tdesign-vue-next')['Button'];
    TSpace: typeof import('tdesign-vue-next')['Space'];
  }
}
